- name: Front-end
  description: Responsive Web Design, UI, Animation
  skills:
  - skillName: Languages
    canDo:
    - Javascript
    - HTML
    - CSS
    - Sass
  - skillName: Libraries
    canDo:
    - React
    - Mui
  - skillName: Developer Tools
    canDo:
    - Git
    - npm
  - skillName: Designing Tools
    canDo:
    - Figma

- name: Back-end
  description: api, rdbms, nosql
  skills:
  - skillName: Languages
    canDo:
    - python
    - sql
    - Javascript
    - ruby
    - liquid
  - skillName: Developer Tools
    canDo:
    - Node js
    - Jekyll
    - Git
    - npm
  - skillName: Framework
    canDo:
    - Flask

- name: Desktop Apps
  description: Windows, linux apps
  skills:
  - skillName: Language
    canDo:
    - Javascript
    - CSS
    - HTML
    - Sass
  - skillName: Libraries
    canDo:
    - React
    - Mui
  - skillName: Developer Tools
    canDo:
    - Node js
    - Git
    - npm
  - skillName: Framework
    canDo:
    - Electron
  - skillName: Design Tools
    canDo:
    - Figma

- name: Scripting
  description: Automation, Web Data Extraction
  skills:
  - skillName: Languages
    canDo:
    - python
    - ruby
    - javascript
  - skillName: Libraries
    canDo:
    - Requests
    - beautifulsoup
  - skillName: Developer Tools
    canDo:
    - Node js
    - Git
    - npm
  - skillName: Framework
    canDo:
    - Appium
    - Selenium